// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobFilter2.Models.Entities;

public partial class BlockForever
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string BlockReason { get; set; }
}