// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobFilter2.Models.Entities
{
    public partial class BlockJobItem
    {
        /// <summary>
        /// 資料編號
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 職缺編號
        /// </summary>
        public string JobCode { get; set; }
    }
}